[build]
builder = "DOCKERFILE"
dockerfilePath = "./apis/ponder/Dockerfile"
watchPatterns = [
    "apis/ponder/**",
    "packages/**",
    "!/*.md",
    "bun.lock",
    "package.json",
]

[deploy]
numReplicas = 1
healthcheckPath = "/ready"
healthcheckTimeout = 172800
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
region = "europe-west4"
